name: data-rescue
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - scipy
  - jupyterlab
  - ipykernel
  - statsmodels
  - notebook
  - pip
  - pip:
    - plotly
    - opencv-contrib-python
    - pypdf[full]